### PR TITLE
Show images/add 'visible' class only when images are loaded

### PR DESCRIPTION
**Pull request by pedrosanta**
Update observer handler to wait for the load event of images (`` elements) before adding the `visible` class

### CODE REVIEW

**Comment by cdowdy** [comment]
hey thanks @pedrosanta, are you or anyone else you know of using this for anthing that isn't an image?  

I ask because originally this was for only images and if we're only dealing with images then we can shorten the pull to something like:  

```javascript  
  change.target.addEventListener('load', () => {
    change.target.classList.add('visible');
  });
```

**Comment by pedrosanta** [comment]
Hi @cdowdy , actually I'm using for images as well—just thought it would be safer that way.

But, yhea, if that's an assumption we can shorten it like you suggested yes. Let me update the branch and ping back to you.

**Comment by pedrosanta** [comment]
Hi @cdowdy , just removed the image tag/element check. Feel free to check if it's good for merging, or if we should adjust anything further.

**Comment by cdowdy** [comment]
hey thanks @pedrosanta this is great! I'll merge this and once I get a little more time I'll create a new release and publish that.  

Thanks so much!

**Pull request merged**
